name: Daily Tweet

on:
  schedule:
    - cron: '0 9 * * *' # Every day at 9:00 UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - name: Run tweet script
        id: tweet
        run: |
          node tweet.js
        env:
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_REFRESH_TOKEN: ${{ secrets.TWITTER_REFRESH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Update Twitter Refresh Token Secret
        if: steps.tweet.outputs.new_refresh_token != ''
        uses: kornicameister/gh-secrets-action@master
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          secrets: |
            TWITTER_REFRESH_TOKEN: ${{ steps.tweet.outputs.new_refresh_token }}
# Note: You must add a PERSONAL_ACCESS_TOKEN secret with repo scope for this to work. 